# Generated by Django 5.2.5 on 2025-08-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='group_id',
            new_name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.questions'),
        ),
    ]
